Arbol
T Arbol< T >::dato_raiz_
Raiz del arbol.
Referenced by Arbol< T * >::ACola, Arbol< T * >::Arbol, Arbol< T * >::borrar, Arbol< T >::borrar, Arbol< T * >::borrarOrden, Arbol< T >::borrarOrden, Arbol< T * >::Destruir, Arbol< T * >::EsHoja, Arbol< T >::EsHoja, Arbol< T * >::insertar, Arbol< T >::insertar, Arbol< T * >::pertenece, Arbol< T >::pertenece, Arbol< T * >::raiz, Arbol< T >::raiz.
Arbol<T>* Arbol< T >::hizq_
Referenced by Arbol< T * >::Arbol, Arbol< T * >::borrar, Arbol< T >::borrar, Arbol< T * >::borrarOrden, Arbol< T >::borrarOrden, Arbol< T * >::Destruir, Arbol< T * >::DobleRotarDerecha, Arbol< T >::DobleRotarDerecha, Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar, Arbol< T * >::EsHoja, Arbol< T >::EsHoja, Arbol< T * >::hijoIzq, Arbol< T * >::insertar, Arbol< T >::insertar, Arbol< T * >::NodosNivel, Arbol< T * >::NumNodos, Arbol< T >::NumNodos, Arbol< T * >::Profundidad, Arbol< T >::Profundidad, Arbol< T * >::RotarDerecha, Arbol< T >::RotarDerecha, Arbol< T * >::~Arbol.
Arbol<T> * Arbol< T >::hder_
Estos atributos son las 2 ramas del arbol.
Referenced by Arbol< T * >::Arbol, Arbol< T * >::borrar, Arbol< T >::borrar, Arbol< T * >::borrarOrden, Arbol< T >::borrarOrden, Arbol< T * >::Destruir, Arbol< T * >::DobleRotarIzquierda, Arbol< T >::DobleRotarIzquierda, Arbol< T * >::Equilibrado, Arbol< T >::Equilibrado, Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar, Arbol< T * >::EsHoja, Arbol< T >::EsHoja, Arbol< T * >::FactorBalanceo, Arbol< T >::FactorBalanceo, Arbol< T * >::hijoDer, Arbol< T * >::insertar, Arbol< T >::insertar, Arbol< T * >::NodosNivel, Arbol< T * >::NumNodos, Arbol< T >::NumNodos, Arbol< T * >::Profundidad, Arbol< T >::Profundidad, Arbol< T * >::RotarIzquierda, Arbol< T >::RotarIzquierda, Arbol< T * >::~Arbol.
bool Arbol< T >::vacio_
Indica si un arbol esta vacio(es decir, no tenemos que tener en cuenta lo que contenga).
Referenced by Arbol< T * >::Arbol, Arbol< T * >::borrar, Arbol< T >::borrar, Arbol< T * >::insertar, Arbol< T >::insertar, Arbol< T * >::vacio, Arbol< T >::vacio, Arbol< T * >::~Arbol, Arbol< T >::~Arbol.
Arbol< T >::Arbol()
Constructor por defecto. Inicializa un objeto de tipo Arbol "" No recibe parametros Devuelve un objeto tipo Arbol inicializado
References DEPURAR_ARBOL_MSG.
Referenced by Arbol< T * >::insertar, Arbol< T >::insertar.
Arbol< T >::Arbol(Arbol *hizq_, const T &dato, Arbol *hder_)
Constructor parametrizado. Inicializa un objeto de tipo Arbol hizq_ Hijo izquierdo del árbol a crear dato dato a insertar en la raíz hder_ Hijo derecho del árbol a crear Devuelve un objeto de tipo Arbol inicializado
References DEPURAR_ARBOL_MSG.
Arbol< T > * Arbol< T >::hijoIzq() const
Devuelve un objeto Arbol con el subárbol izquierdo
Referenced by Arbol< T * >::borrarOrden, Arbol< T >::borrarOrden, Arbol< T * >::Destruir, Arbol< T * >::insertar, Arbol< T >::insertar, Arbol< T * >::pertenece, Arbol< T >::pertenece, Arbol< T * >::~Arbol, Arbol< T >::~Arbol.
Arbol< T > * Arbol< T >::hijoDer() const
Devuelve un objeto Arbol con el subárbol derecho
Referenced by Arbol< T * >::ACola, Arbol< T * >::Destruir, Arbol< T * >::insertar, Arbol< T >::insertar, Arbol< T * >::pertenece, Arbol< T >::pertenece, Arbol< T * >::~Arbol, Arbol< T >::~Arbol.
T Arbol< T >::raiz() const
Devuelve el valor almacenado en la raíz
References Arbol< T >::dato_raiz_.
Referenced by Arbol< T * >::InOrden, Arbol< T >::InOrden, Arbol< T * >::PostOrden, Arbol< T >::PostOrden.
bool Arbol< T >::vacio() const
Devuelve true si el árbol está vacío
References Arbol< T >::vacio_.
Referenced by Arbol< T * >::borrar, Arbol< T >::borrar, Arbol< T * >::borrarOrden, Arbol< T >::borrarOrden, Arbol< T * >::Destruir, Arbol< T * >::insertar, Arbol< T >::insertar, Arbol< T * >::pertenece, Arbol< T >::pertenece, Arbol< T * >::~Arbol, Arbol< T >::~Arbol.
bool Arbol< T >::insertar(const T &dato)
Inserta el valor dato en el Árbol Binario de Búsqueda dato Valor a insertar Retorna true si se insertó correctamente
References Arbol< T >::Arbol, Arbol< T >::dato_raiz_, DEPURAR_ARBOL_MSG, Arbol< T >::hder_, Arbol< T >::hijoDer, Arbol< T >::hijoIzq, Arbol< T >::hizq_, Arbol< T >::insertar, Arbol< T >::vacio, Arbol< T >::vacio_.
Referenced by Arbol< T * >::insertar, Arbol< T >::insertar.
bool Arbol< T >::pertenece(const T &dato) const
Indica si el valor dato existe en el Árbol Binario de Búsqueda dato Valor a insertar Devuelve true si encuentra un nodo con ese valor
References Arbol< T >::dato_raiz_, DEPURAR_ARBOL_MSG, Arbol< T >::hijoDer, Arbol< T >::hijoIzq, Arbol< T >::pertenece, Arbol< T >::vacio.
Referenced by Arbol< T * >::pertenece, Arbol< T >::pertenece.
void Arbol< T >::borrar(const T &dato)
Elimina el nodo que contenga el valor dato dato Valor a eliminar No devuelve nada
References Arbol< T >::borrarOrden, Arbol< T >::dato_raiz_, DEPURAR_ARBOL_MSG, Arbol< T >::hder_, Arbol< T >::hizq_, Arbol< T >::vacio, Arbol< T >::vacio_.
int Arbol< T >::Profundidad() const
Metodo que halla la profundidad del arbol profundidad del arbol
References Arbol< T >::hder_, Arbol< T >::hizq_, Arbol< T >::maximo.
bool Arbol< T >::EsHoja() const
Comprueba si un arbol es hoja o no true si el arbol es hoja(no tiene hijos), false en caso contrario
Referenced by Arbol< T * >::EsHoja, Arbol< T >::EsHoja.
bool Arbol< T >::EsHoja(const T &dato) const
Modulo que calcula si un nodo es una hoja o no. dato dato que buscamos true si el nodo que buscamos es hoja, false en caso contrario o si esta vacio.
References Arbol< T >::dato_raiz_, Arbol< T >::EsHoja, Arbol< T >::hder_, Arbol< T >::hizq_.
int Arbol< T >::NodosNivel(const int &nivel) const
Metodo que nos devuelve el numero de nodos que tiene un nivel. nivel nivel en el que hallar el numero de nodos numero de nodos que tiene el nivel
References Arbol< T >::NodosNivel.
Referenced by Arbol< T >::NodosNivel.
void Arbol< T >::NumNodos(int &hojas, int &nodos) const
Metodo que devuelve por parametro el numero de hojas y nudos de un arbol. hojas numero de hojas que contiene el arbol nodos numero de nudos(nodos internos) que contiene el arbol hojas y nodos deben valer 0
References Arbol< T >::hder_, Arbol< T >::hizq_.
int Arbol< T >::NumNodos(const int &nivel) const
Devuelve el numero de nodos que contiene un arbol hasta un nivel dado nivel ultimo nivel a contar numero de nodos que tiene un arbol hasta el nivel "nivel"
References Arbol< T >::hder_, Arbol< T >::hizq_.
int Arbol< T >::NumNodos() const
Devuelve el numero de nodos que contiene un arbol numero de nodos que tiene un arbol
References Arbol< T >::hder_, Arbol< T >::hizq_.
bool Arbol< T >::Equilibrado() const
Comprueba si un arbol esta correctamente balanceado true si el arbol esta equilibrado false en caso contrario
References Arbol< T >::FactorBalanceo, Arbol< T >::hder_.
Referenced by Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar.
Arbol< T > * Arbol< T >::Equilibrar()
Equilibra el arbol usando las funciones de rotar retorna el arbol equilibrado
References Arbol< T >::DobleRotarDerecha, Arbol< T >::DobleRotarIzquierda, Arbol< T >::Equilibrado, Arbol< T >::Equilibrar, Arbol< T >::hder_, Arbol< T >::hizq_, Arbol< T >::RotarDerecha, Arbol< T >::RotarIzquierda.
Referenced by Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar.
bool Arbol< T >::operator==(const Arbol &A) const
Sobrecarga del operador == A segundo elemento a comparar bool si son iguales, false en caso contrario
bool Arbol< T >::operator!=(const Arbol &A) const
Sobrecarga del operador != A segundo elemento a comparar bool si no son iguales, false en caso contrario
void Arbol< T >::InOrden() const
Metodo que muestra el arbol con un recorrido en profundidad inorden
References Arbol< T >::raiz.
void Arbol< T >::PreOrden() const
Metodo que muestra el arbol con un recorrido en profundidad preorden
void Arbol< T >::PostOrden() const
Metodo que muestra el arbol con un recorrido en profundidad postorden
References Arbol< T >::raiz.
Arbol< T >::~Arbol()
Destructor por defecto. Destruye un objeto de tipo Arbol "" No recibe parametros No devuelve nada
References DEPURAR_ARBOL_MSG, Arbol< T >::hijoDer, Arbol< T >::hijoIzq, Arbol< T >::vacio, Arbol< T >::vacio_.
Arbol< T > * Arbol< T >::borrarOrden(const T &dato)
Función privada auxiliar para realizar el borrado de un nodo. Reestructura el árbol tras el borrado dato Valor a eliminar Devuelve el árbol resultado del borrado
References Arbol< T >::dato_raiz_, DEPURAR_ARBOL_MSG, Arbol< T >::hder_, Arbol< T >::hijoIzq, Arbol< T >::hizq_, Arbol< T >::vacio.
Referenced by Arbol< T * >::borrar, Arbol< T >::borrar.
int Arbol< T >::maximo(const int &a, const int &b) const
Metodo que devuelve el maximo de dos enteros a primer entero b segundo entero el mayor de los 2 enteros, en caso de ser iguales devuelve el segundo
Referenced by Arbol< T * >::Profundidad, Arbol< T >::Profundidad.
Arbol< T > * Arbol< T >::RotarDerecha()
Gira en sentido de las manecillas de reloj P(el puntero al nodo con factor de balance no permitido) alrededor de Q(Hijo izquierdo de P) retorna el arbol rotado
References Arbol< T >::hizq_.
Referenced by Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar.
Arbol< T > * Arbol< T >::RotarIzquierda()
Gira en sentido de contrario a las manecillas de reloj P(el puntero al nodo con factor de balance no permitido) alrededor de Q(Hijo izquierdo de P) retorna el arbol rotado
References Arbol< T >::hder_.
Referenced by Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar.
Arbol< T > * Arbol< T >::DobleRotarDerecha()
Rotacion a la izquierda de Q alrededor de R seguida de una rotacion a la derecha de P alrededor de R. retorna el arbol rotado
References Arbol< T >::hizq_.
Referenced by Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar.
Arbol< T > * Arbol< T >::DobleRotarIzquierda()
Rotacion a la derecha de Q alrededor de R seguida de una rotacion a la izquierda de P alrededor de R retorna el arbol rotado
References Arbol< T >::hder_.
Referenced by Arbol< T * >::Equilibrar, Arbol< T >::Equilibrar.
int Arbol< T >::FactorBalanceo() const
Halla el factor de balanceo de el arbol actual el factor de balanceo
References Arbol< T >::hder_.
Referenced by Arbol< T * >::Equilibrado, Arbol< T >::Equilibrado.
bool Arbol< T >::Iguales(const Arbol *A) const
Funcion auxiliar para la sobrecarga del operador == A segundo parametro a comparara true si los 2 arboles son iguales, false en caso contrario