testing::internal::String
const char* testing::internal::String::c_str_
Referenced by operator=, ~String.
static const char* testing::internal::String::ShowCString(const char *c_str)
static String testing::internal::String::ShowCStringQuoted(const char *c_str)
static const char* testing::internal::String::CloneCString(const char *c_str)
static bool testing::internal::String::CStringEquals(const char *lhs, const char *rhs)
static String testing::internal::String::ShowWideCString(const wchar_t *wide_c_str)
Referenced by testing::Message::operator<<.
static String testing::internal::String::ShowWideCStringQuoted(const wchar_t *wide_c_str)
static bool testing::internal::String::WideCStringEquals(const wchar_t *lhs, const wchar_t *rhs)
static bool testing::internal::String::CaseInsensitiveCStringEquals(const char *lhs, const char *rhs)
static bool testing::internal::String::CaseInsensitiveWideCStringEquals(const wchar_t *lhs, const wchar_t *rhs)
static String testing::internal::String::Format(const char *format,...)
Referenced by testing::internal::FormatFileLocation.
testing::internal::String::String()
testing::internal::String::String(const char *c_str)
testing::internal::String::String(const char *buffer, size_t len)
testing::internal::String::String(const String &str)
testing::internal::String::~String()
References c_str_.
bool testing::internal::String::empty() const
int testing::internal::String::Compare(const String &rhs) const
bool testing::internal::String::operator==(const char *c_str) const
bool testing::internal::String::operator<(const String &rhs) const
bool testing::internal::String::operator!=(const char *c_str) const
bool testing::internal::String::EndsWith(const char *suffix) const
bool testing::internal::String::EndsWithCaseInsensitive(const char *suffix) const
int testing::internal::String::GetLength() const
const char* testing::internal::String::c_str() const
Referenced by testing::internal::FilePath::c_str, testing::AssertionResult::failure_message, testing::TestPartResult::file_name, testing::TestPartResult::message, testing::AssertionResult::operator bool, testing::internal::operator<<, testing::TestPartResult::summary.
void testing::internal::String::Set(const char *c_str, size_t length)
const String& testing::internal::String::operator=(const char *c_str)
const String& testing::internal::String::operator=(const String &rhs)
References c_str_.