testing::internal::FloatingPoint
typedef TypeWithSize<sizeof(RawType)>::UInt testing::internal::FloatingPoint< RawType >::Bits
const size_t testing::internal::FloatingPoint< RawType >::kBitCount
const size_t testing::internal::FloatingPoint< RawType >::kFractionBitCount
const size_t testing::internal::FloatingPoint< RawType >::kExponentBitCount
const Bits testing::internal::FloatingPoint< RawType >::kSignBitMask
Referenced by testing::internal::FloatingPoint< RawType >::sign_bit, testing::internal::FloatingPoint< RawType >::SignAndMagnitudeToBiased.
const Bits testing::internal::FloatingPoint< RawType >::kFractionBitMask
Referenced by testing::internal::FloatingPoint< RawType >::fraction_bits.
const Bits testing::internal::FloatingPoint< RawType >::kExponentBitMask
Referenced by testing::internal::FloatingPoint< RawType >::exponent_bits, testing::internal::FloatingPoint< RawType >::Infinity, testing::internal::FloatingPoint< RawType >::is_nan.
const size_t testing::internal::FloatingPoint< RawType >::kMaxUlps
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals.
RawType testing::internal::FloatingPoint< RawType >::value_
Referenced by testing::internal::FloatingPoint< RawType >::ReinterpretBits.
Bits testing::internal::FloatingPoint< RawType >::bits_
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals, testing::internal::FloatingPoint< RawType >::bits, testing::internal::FloatingPoint< RawType >::exponent_bits, testing::internal::FloatingPoint< RawType >::fraction_bits, testing::internal::FloatingPoint< RawType >::ReinterpretBits, testing::internal::FloatingPoint< RawType >::sign_bit.
union testing::internal::FloatingPoint::@0 testing::internal::FloatingPoint< RawType >::@1
testing::internal::FloatingPoint< RawType >::FloatingPoint(const RawType &x)
const Bits& testing::internal::FloatingPoint< RawType >::bits() const
References testing::internal::FloatingPoint< RawType >::bits_.
Bits testing::internal::FloatingPoint< RawType >::exponent_bits() const
References testing::internal::FloatingPoint< RawType >::bits_, testing::internal::FloatingPoint< RawType >::kExponentBitMask.
Referenced by testing::internal::FloatingPoint< RawType >::is_nan.
Bits testing::internal::FloatingPoint< RawType >::fraction_bits() const
References testing::internal::FloatingPoint< RawType >::bits_, testing::internal::FloatingPoint< RawType >::kFractionBitMask.
Referenced by testing::internal::FloatingPoint< RawType >::is_nan.
Bits testing::internal::FloatingPoint< RawType >::sign_bit() const
References testing::internal::FloatingPoint< RawType >::bits_, testing::internal::FloatingPoint< RawType >::kSignBitMask.
bool testing::internal::FloatingPoint< RawType >::is_nan() const
References testing::internal::FloatingPoint< RawType >::exponent_bits, testing::internal::FloatingPoint< RawType >::fraction_bits, testing::internal::FloatingPoint< RawType >::kExponentBitMask.
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals.
bool testing::internal::FloatingPoint< RawType >::AlmostEquals(const FloatingPoint &rhs) const
References testing::internal::FloatingPoint< RawType >::bits_, testing::internal::FloatingPoint< RawType >::DistanceBetweenSignAndMagnitudeNumbers, testing::internal::FloatingPoint< RawType >::is_nan, testing::internal::FloatingPoint< RawType >::kMaxUlps.
static RawType testing::internal::FloatingPoint< RawType >::ReinterpretBits(const Bits bits)
References testing::internal::FloatingPoint< RawType >::bits_, testing::internal::FloatingPoint< RawType >::value_.
Referenced by testing::internal::FloatingPoint< RawType >::Infinity.
static RawType testing::internal::FloatingPoint< RawType >::Infinity()
References testing::internal::FloatingPoint< RawType >::kExponentBitMask, testing::internal::FloatingPoint< RawType >::ReinterpretBits.
static Bits testing::internal::FloatingPoint< RawType >::SignAndMagnitudeToBiased(const Bits &sam)
References testing::internal::FloatingPoint< RawType >::kSignBitMask.
Referenced by testing::internal::FloatingPoint< RawType >::DistanceBetweenSignAndMagnitudeNumbers.
static Bits testing::internal::FloatingPoint< RawType >::DistanceBetweenSignAndMagnitudeNumbers(const Bits &sam1, const Bits &sam2)
References testing::internal::FloatingPoint< RawType >::SignAndMagnitudeToBiased.
Referenced by testing::internal::FloatingPoint< RawType >::AlmostEquals.