testing::internal::FilePath
String testing::internal::FilePath::pathname_
Referenced by c_str, Set, ToString.
testing::internal::FilePath::FilePath()
testing::internal::FilePath::FilePath(const FilePath &rhs)
testing::internal::FilePath::FilePath(const char *pathname)
References Normalize.
testing::internal::FilePath::FilePath(const String &pathname)
References Normalize.
FilePath& testing::internal::FilePath::operator=(const FilePath &rhs)
References Set.
void testing::internal::FilePath::Set(const FilePath &rhs)
References pathname_.
Referenced by operator=.
String testing::internal::FilePath::ToString() const
References pathname_.
const char* testing::internal::FilePath::c_str() const
References testing::internal::String::c_str, pathname_.
Referenced by IsEmpty.
bool testing::internal::FilePath::IsEmpty() const
References c_str.
FilePath testing::internal::FilePath::RemoveTrailingPathSeparator() const
FilePath testing::internal::FilePath::RemoveDirectoryName() const
FilePath testing::internal::FilePath::RemoveFileName() const
FilePath testing::internal::FilePath::RemoveExtension(const char *extension) const
bool testing::internal::FilePath::CreateDirectoriesRecursively() const
bool testing::internal::FilePath::CreateFolder() const
bool testing::internal::FilePath::FileOrDirectoryExists() const
bool testing::internal::FilePath::DirectoryExists() const
bool testing::internal::FilePath::IsDirectory() const
bool testing::internal::FilePath::IsRootDirectory() const
static FilePath testing::internal::FilePath::GetCurrentDir()
static FilePath testing::internal::FilePath::MakeFileName(const FilePath &directory, const FilePath &base_name, int number, const char *extension)
static FilePath testing::internal::FilePath::GenerateUniqueFileName(const FilePath &directory, const FilePath &base_name, const char *extension)
void testing::internal::FilePath::Normalize()
Referenced by FilePath.