Puerta
TipoEstado Puerta::estado_
atributo que nos indica si la puerta esta NOCONFIGURADA(0), CERRADA(1) o ABIERTA(2)
int Puerta::altura_
atributo que inidica la altura que no debe superar el arbol para poder abrir la puerta
Arbol<Llave*>* Puerta::combinacion_
atributo tipo arbol binario de busqueda que alamacena la combinacion correcta.
Arbol<Llave*>* Puerta::probadas_
atributo tipo arbol binario de busqueda que almacena las llaves probadas en la puerta.
ColaGen<Llave*>* Puerta::copia_combinacion_
atributo que contiene una copia de la combinacion secreta para poder reconfigur la puerta.
Puerta::Puerta()
Constructor por defecto de la clase Puerta
Puerta::Puerta(const int &alt)
Constructor parametrizado de la clase Puerta alt parametro que se copiara al atributo altura_
void Puerta::Configurar(ColaGen< Llave * > *cop)
Copia de una cola a copia_combinacion_ todas las llaves cop parametro desde el cual se va a copiar
bool Puerta::ProbarLlave(Llave *L)
Prueba una llave: intenta insertarla en probadas, si no puede(por que ya se encuentra en probadas) llama al metodo de alerta, si no se encuentra en probadas pero si en combinacion, la elimina de combinacion, la inserta en probadas y devuelve true y si no se enceutra en ninguna de las 2, la inserta en probadas y devuelve false L puntero a llavellave que queremos probar true si pertenece a la combinacion y no ha sido probada previamente, false si no se encuentra en la combinacion o a sido probada previamente.
Referenced by Planta::ProbarLlave.
bool Puerta::ProbarLlave(const Llave &L2)
Prueba una llave: intenta insertarla en probadas, si no puede(por que ya se encuentra en probadas) llama al metodo de alerta, si no se encuentra en probadas pero si en combinacion, la elimina de combinacion, la inserta en probadas y devuelve true y si no se enceutra en ninguna de las 2, la inserta en probadas y devuelve false L2 llave que queremos probar true si pertenece a la combinacion y no ha sido probada previamente, false si no se encuentra en la combinacion o a sido probada previamente.
bool Puerta::Abrir()
Intenta abrir una puerta comprobando si se cumplen las condiciones. true si se consigue abrir correctamente, false en caso contrario
Referenced by Planta::AbrirPuerta.
bool Puerta::Cerrar()
Metodo que cierra la puerta, copiando la configuracion desde copia_configuracion_ a configuracion_ y borra el arbol de probadas_ true si esta abierta y se cierra, false en otro caso
Referenced by Planta::CerrarPuerta.
Arbol< Llave * > * Puerta::get_combinacion()
Obtiene el atributo combinacion_, que es un arbol arbol con combinacion_
Arbol< Llave * > * Puerta::get_probadas()
Obtiene el atributo probadas_, que es un arbol arbol con probadas_
ColaGen< Llave * > * Puerta::get_copia_combinacion()
Obtiene copia_combinacion cola generica de punteros a llaves con copia_combinacion_
TipoEstado Puerta::get_estado()
Devuelve el estado de la puerta (0-NOCONFIGURAR, 1-CERRADA, 2-ABIERTA) Tipoestado con la informacion
Referenced by Planta::EstadoPuerta.
Puerta::~Puerta()
Destructor de la clase Puerta
void Puerta::Alarma()
Metodo en respuesta a que se han probado 2 veces la misma llave
ostream& operator<<(ostream &flujo, const Puerta &P)
Sobrecarga del operador << flujo flujo al que se le pasara la informacion P Puerta a mostrar flujo con los datos
bool Puerta::set_combinacion()
Copia la combinacion desde copia_combinacion_ true si en copia_combinacion_ hay datos, false en caso contrario