testing::internal::linked_ptr_internal
linked_ptr_internal const* testing::internal::linked_ptr_internal::next_
Referenced by depart, join, join_new.
void testing::internal::linked_ptr_internal::join_new()
References next_.
Referenced by testing::internal::linked_ptr< T >::capture, testing::internal::linked_ptr< T >::copy.
void testing::internal::linked_ptr_internal::join(linked_ptr_internal const *ptr)
References testing::internal::g_linked_ptr_mutex, next_.
Referenced by testing::internal::linked_ptr< T >::copy.
bool testing::internal::linked_ptr_internal::depart()
References testing::internal::g_linked_ptr_mutex, next_.
Referenced by testing::internal::linked_ptr< T >::depart, testing::internal::linked_ptr< T >::release.