testing::internal::linked_ptr
typedef T testing::internal::linked_ptr< T >::element_type
friend class linked_ptr
T* testing::internal::linked_ptr< T >::value_
Referenced by testing::internal::linked_ptr< T >::capture, testing::internal::linked_ptr< T >::copy, testing::internal::linked_ptr< T >::depart, testing::internal::linked_ptr< T >::get, testing::internal::linked_ptr< T >::operator *, testing::internal::linked_ptr< T >::operator!=, testing::internal::linked_ptr< T >::operator->, testing::internal::linked_ptr< T >::operator==, testing::internal::linked_ptr< T >::release.
linked_ptr_internal testing::internal::linked_ptr< T >::link_
Referenced by testing::internal::linked_ptr< T >::capture, testing::internal::linked_ptr< T >::copy, testing::internal::linked_ptr< T >::depart, testing::internal::linked_ptr< T >::release.
testing::internal::linked_ptr< T >::linked_ptr(T *ptr=NULL)
References testing::internal::linked_ptr< T >::capture.
testing::internal::linked_ptr< T >::~linked_ptr()
References testing::internal::linked_ptr< T >::depart.
testing::internal::linked_ptr< T >::linked_ptr(linked_ptr< U > const &ptr)
References testing::internal::linked_ptr< T >::copy.
testing::internal::linked_ptr< T >::linked_ptr(linked_ptr const &ptr)
References testing::internal::linked_ptr< T >::copy.
linked_ptr& testing::internal::linked_ptr< T >::operator=(linked_ptr< U > const &ptr)
References testing::internal::linked_ptr< T >::copy, testing::internal::linked_ptr< T >::depart.
linked_ptr& testing::internal::linked_ptr< T >::operator=(linked_ptr const &ptr)
References testing::internal::linked_ptr< T >::copy, testing::internal::linked_ptr< T >::depart.
void testing::internal::linked_ptr< T >::reset(T *ptr=NULL)
References testing::internal::linked_ptr< T >::capture, testing::internal::linked_ptr< T >::depart.
T* testing::internal::linked_ptr< T >::get() const
References testing::internal::linked_ptr< T >::value_.
Referenced by testing::internal::linked_ptr< T >::copy, testing::internal::operator!=, testing::internal::linked_ptr< T >::operator!=, testing::internal::operator==, testing::internal::linked_ptr< T >::operator==.
T* testing::internal::linked_ptr< T >::operator->() const
References testing::internal::linked_ptr< T >::value_.
T& testing::internal::linked_ptr< T >::operator *() const
References testing::internal::linked_ptr< T >::value_.
T* testing::internal::linked_ptr< T >::release()
References testing::internal::linked_ptr_internal::depart, testing::internal::linked_ptr< T >::link_, testing::internal::linked_ptr< T >::value_.
bool testing::internal::linked_ptr< T >::operator==(T *p) const
References testing::internal::linked_ptr< T >::value_.
bool testing::internal::linked_ptr< T >::operator!=(T *p) const
References testing::internal::linked_ptr< T >::value_.
bool testing::internal::linked_ptr< T >::operator==(linked_ptr< U > const &ptr) const
References testing::internal::linked_ptr< T >::get, testing::internal::linked_ptr< T >::value_.
bool testing::internal::linked_ptr< T >::operator!=(linked_ptr< U > const &ptr) const
References testing::internal::linked_ptr< T >::get, testing::internal::linked_ptr< T >::value_.
void testing::internal::linked_ptr< T >::depart()
References testing::internal::linked_ptr_internal::depart, testing::internal::linked_ptr< T >::link_, testing::internal::linked_ptr< T >::value_.
Referenced by testing::internal::linked_ptr< T >::operator=, testing::internal::linked_ptr< T >::reset, testing::internal::linked_ptr< T >::~linked_ptr.
void testing::internal::linked_ptr< T >::capture(T *ptr)
References testing::internal::linked_ptr_internal::join_new, testing::internal::linked_ptr< T >::link_, testing::internal::linked_ptr< T >::value_.
Referenced by testing::internal::linked_ptr< T >::linked_ptr, testing::internal::linked_ptr< T >::reset.
void testing::internal::linked_ptr< T >::copy(linked_ptr< U > const *ptr)
References testing::internal::linked_ptr< T >::get, testing::internal::linked_ptr_internal::join, testing::internal::linked_ptr_internal::join_new, testing::internal::linked_ptr< T >::link_, testing::internal::linked_ptr< T >::value_.
Referenced by testing::internal::linked_ptr< T >::linked_ptr, testing::internal::linked_ptr< T >::operator=.