testing::internal
GTestLogSeverity
const char testing::internal::kDeathTestStyleFlag[][]
const char testing::internal::kInternalRunDeathTestFlag[][]
int testing::internal::g_init_gtest_count
const char testing::internal::kStackTraceMarker[][]
class testing::internal::ScopedTrace testing::internal::GTEST_ATTRIBUTE_UNUSED_
Mutex testing::internal::g_linked_ptr_mutex
Referenced by testing::internal::linked_ptr_internal::depart, testing::internal::linked_ptr_internal::join.
const BiggestInt testing::internal::kMaxBiggestInt
typedef FloatingPoint<float> testing::internal::Float
typedef FloatingPoint<double> testing::internal::Double
typedef const void* testing::internal::TypeId
typedef void(*) testing::internal::SetUpTestCaseFunc()()
typedef void(*) testing::internal::TearDownTestCaseFunc()()
typedef ::std::stringstream testing::internal::StrStream
typedef GTestMutexLock testing::internal::MutexLock
typedef bool_constant<false> testing::internal::false_type
typedef bool_constant<true> testing::internal::true_type
typedef long long testing::internal::BiggestInt
typedef TypeWithSize<4>::Int testing::internal::Int32
typedef TypeWithSize<4>::UInt testing::internal::UInt32
typedef TypeWithSize<8>::Int testing::internal::Int64
typedef TypeWithSize<8>::UInt testing::internal::UInt64
typedef TypeWithSize<8>::Int testing::internal::TimeInMillis
String testing::internal::StreamableToString(const T &streamable)
Referenced by FormatForFailureMessage.
String testing::internal::FormatForComparisonFailureMessage(const T1 &value, const T2 &)
References FormatForFailureMessage.
Referenced by CmpHelperEQ.
AssertionResult testing::internal::CmpHelperEQ(const char *expected_expression, const char *actual_expression, const T1 &expected, const T2 &actual)
References testing::AssertionSuccess, EqFailure, FormatForComparisonFailureMessage.
Referenced by testing::internal::EqHelper< true >::Compare, testing::internal::EqHelper< lhs_is_null_literal >::Compare.
AssertionResult testing::internal::CmpHelperEQ(const char *expected_expression, const char *actual_expression, BiggestInt expected, BiggestInt actual)
AssertionResult testing::internal::CmpHelperSTREQ(const char *expected_expression, const char *actual_expression, const char *expected, const char *actual)
AssertionResult testing::internal::CmpHelperSTRCASEEQ(const char *expected_expression, const char *actual_expression, const char *expected, const char *actual)
AssertionResult testing::internal::CmpHelperSTRNE(const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
AssertionResult testing::internal::CmpHelperSTRCASENE(const char *s1_expression, const char *s2_expression, const char *s1, const char *s2)
AssertionResult testing::internal::CmpHelperSTREQ(const char *expected_expression, const char *actual_expression, const wchar_t *expected, const wchar_t *actual)
AssertionResult testing::internal::CmpHelperSTRNE(const char *s1_expression, const char *s2_expression, const wchar_t *s1, const wchar_t *s2)
AssertionResult testing::internal::CmpHelperFloatingPointEQ(const char *expected_expression, const char *actual_expression, RawType expected, RawType actual)
References testing::AssertionSuccess, EqFailure, StrStreamToString.
AssertionResult testing::internal::DoubleNearPredFormat(const char *expr1, const char *expr2, const char *abs_error_expr, double val1, double val2, double abs_error)
testing::internal::GTEST_DECLARE_string_(internal_run_death_test)
char testing::internal::IsNullLiteralHelper(Secret *p)
testing::internal::char(&IsNullLiteralHelper(...))[2]
String testing::internal::AppendUserMessage(const String &gtest_msg, const Message &user_msg)
String testing::internal::FormatForFailureMessage(const T &value)
References StreamableToString.
Referenced by FormatForComparisonFailureMessage.
String testing::internal::FormatForFailureMessage(T *pointer)
References StreamableToString.
String testing::internal::FormatForFailureMessage(char ch)
String testing::internal::FormatForFailureMessage(wchar_t wchar)
AssertionResult testing::internal::EqFailure(const char *expected_expression, const char *actual_expression, const String &expected_value, const String &actual_value, bool ignoring_case)
Referenced by CmpHelperEQ, CmpHelperFloatingPointEQ.
TypeId testing::internal::GetTypeId()
TypeId testing::internal::GetTestTypeId()
String testing::internal::FormatFileLocation(const char *file, int line)
References testing::internal::String::Format.
TestInfo* testing::internal::MakeAndRegisterTestInfo(const char *test_case_name, const char *name, const char *test_case_comment, const char *comment, TypeId fixture_class_id, SetUpTestCaseFunc set_up_tc, TearDownTestCaseFunc tear_down_tc, TestFactoryBase *factory)
String testing::internal::GetCurrentOsStackTraceExceptTop(UnitTest *unit_test, int skip_count)
int testing::internal::GetFailedPartCount(const TestResult *result)
bool testing::internal::operator==(T *ptr, const linked_ptr< T > &x)
References testing::internal::linked_ptr< T >::get.
bool testing::internal::operator!=(T *ptr, const linked_ptr< T > &x)
References testing::internal::linked_ptr< T >::get.
linked_ptr<T> testing::internal::make_linked_ptr(T *ptr)
void testing::internal::GTestLog(GTestLogSeverity severity, const char *file, int line, const char *msg)
void testing::internal::LogToStderr()
void testing::internal::FlushInfoLog()
size_t testing::internal::GetThreadCount()
const char* testing::internal::GetEnv(const char *name)
void testing::internal::abort()
Referenced by testing::internal::GTestCheckProvider::~GTestCheckProvider.
bool testing::internal::ParseInt32(const Message &src_text, const char *str, Int32 *value)
bool testing::internal::BoolFromGTestEnv(const char *flag, bool default_val)
Int32 testing::internal::Int32FromGTestEnv(const char *flag, Int32 default_val)
const char* testing::internal::StringFromGTestEnv(const char *flag, const char *default_val)
inline ::std::ostream& testing::internal::operator<<(::std::ostream &os, const String &str)
References testing::internal::String::c_str.
String testing::internal::StrStreamToString(StrStream *stream)
Referenced by CmpHelperFloatingPointEQ, testing::Message::GetString.