testing
TestPartResultType
const int testing::kMaxStackTraceDepth
testing::GTEST_DECLARE_string_(death_test_style)
std::ostream& testing::operator<<(std::ostream &os, const Message &sb)
References testing::Message::GetString.
std::ostream& testing::operator<<(std::ostream &os, const TestPartResult &result)
testing::GTEST_DECLARE_int32_(stack_trace_depth)
testing::GTEST_DECLARE_bool_(show_internal_stack_frames)
AssertionResult testing::AssertionSuccess()
Referenced by AssertPred1Helper, AssertPred2Helper, AssertPred3Helper, AssertPred4Helper, AssertPred5Helper, testing::internal::CmpHelperEQ, testing::internal::CmpHelperFloatingPointEQ.
AssertionResult testing::AssertionFailure(const Message &msg)
Referenced by AssertPred1Helper, AssertPred2Helper, AssertPred3Helper, AssertPred4Helper, AssertPred5Helper.
Environment* testing::AddGlobalTestEnvironment(Environment *env)
References testing::UnitTest::AddEnvironment, testing::UnitTest::GetInstance.
void testing::InitGoogleTest(int *argc, char **argv)
void testing::InitGoogleTest(int *argc, wchar_t **argv)
AssertionResult testing::IsSubstring(const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
AssertionResult testing::IsSubstring(const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
AssertionResult testing::IsNotSubstring(const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
AssertionResult testing::IsNotSubstring(const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
AssertionResult testing::FloatLE(const char *expr1, const char *expr2, float val1, float val2)
AssertionResult testing::DoubleLE(const char *expr1, const char *expr2, double val1, double val2)